services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5020:8080"
    env_file: 
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
        - ${SESSIONS_DIR_PATH}:/app/sessions
        - ${DOWNLOADS_DIR_PATH}:/app/downloads

  db:
    container_name: telegram-logger-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - "52354:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    