// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250422225843_FromIdInMessageLogs")]
    partial class FromIdInMessageLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Database.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Database.Entities.AccountLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ByUserId");

                    b.ToTable("AccountHistory");
                });

            modelBuilder.Entity("Database.Entities.LoggingTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccessHash")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("FromAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("PeerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("PeerId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Database.Entities.Session", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DiedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Database.Entities.UpdateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("LoggingTargetId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("LoggingTargetId");

                    b.ToTable("Updates");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Database.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Database.Entities.UpdateDeleteMessageLog", b =>
                {
                    b.HasBaseType("Database.Entities.UpdateLog");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.ToTable("DeleteMessageUpdates", (string)null);
                });

            modelBuilder.Entity("Database.Entities.UpdateMessageLog", b =>
                {
                    b.HasBaseType("Database.Entities.UpdateLog");

                    b.Property<long>("FromId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MsgDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("PrevEditId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("TextEntities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("PrevEditId");

                    b.ToTable("MessageUpdates", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Account", b =>
                {
                    b.HasOne("Database.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Database.Entities.AccountLog", b =>
                {
                    b.HasOne("Database.Entities.Account", "Account")
                        .WithMany("AccountLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.User", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId");

                    b.Navigation("Account");

                    b.Navigation("ByUser");
                });

            modelBuilder.Entity("Database.Entities.LoggingTarget", b =>
                {
                    b.HasOne("Database.Entities.Account", "FromAccount")
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromAccount");
                });

            modelBuilder.Entity("Database.Entities.Session", b =>
                {
                    b.HasOne("Database.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Database.Entities.UpdateLog", b =>
                {
                    b.HasOne("Database.Entities.LoggingTarget", "LoggingTarget")
                        .WithMany("Logs")
                        .HasForeignKey("LoggingTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggingTarget");
                });

            modelBuilder.Entity("Database.Entities.UpdateDeleteMessageLog", b =>
                {
                    b.HasOne("Database.Entities.UpdateLog", null)
                        .WithOne()
                        .HasForeignKey("Database.Entities.UpdateDeleteMessageLog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.UpdateMessageLog", b =>
                {
                    b.HasOne("Database.Entities.UpdateLog", null)
                        .WithOne()
                        .HasForeignKey("Database.Entities.UpdateMessageLog", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.UpdateMessageLog", "PrevEdit")
                        .WithMany()
                        .HasForeignKey("PrevEditId");

                    b.Navigation("PrevEdit");
                });

            modelBuilder.Entity("Database.Entities.Account", b =>
                {
                    b.Navigation("AccountLogs");
                });

            modelBuilder.Entity("Database.Entities.LoggingTarget", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
